# -*- coding: utf-8 -*-
"""day9 AdaBoostClassifier vid13

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oyxIfLXFK0WwiI2kL8SK7ChIyxPNJBGA
"""

import pandas as pd
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

df = pd.concat([train, test], sort = False)
df

df.isnull().sum()

#df.drop('Cabin', axis = 1, inplace = True)
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy = 'mean')
df['Age'] = imp.fit_transform(df[['Age']])
df['Fare'] = imp.fit_transform(df[['Fare']])
imp1 = SimpleImputer(strategy = 'most_frequent')
df['Survived'] = imp1.fit_transform(df[['Survived']])
df['Embarked'] = imp1.fit_transform(df[['Embarked']])

df

X = df.drop(['Ticket','Name'], axis = 1, inplace = True)

df

import numpy as np
numerical_features = ['Fare', 'Age']
from scipy.stats import zscore
z_score = np.abs(zscore(df[numerical_features]))
print(z_score)

from scipy.stats.mstats import winsorize
df['Fare'] = winsorize(df['Fare'], limits = [0.15,0.15])
df['Age'] = winsorize(df['Age'], limits = [0.15,0.15])
df

from sklearn.preprocessing import OrdinalEncoder
en = OrdinalEncoder()
df['Sex'] = en.fit_transform(df[['Sex']])
df['Embarked'] = en.fit_transform(df[['Embarked']])

from sklearn.ensemble import AdaBoostClassifier
ab = AdaBoostClassifier(n_estimators = 45, learning_rate = 1, random_state = 0)
X = df.drop('Survived', axis = 1)
y = df['Survived']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
ab.fit(X_train, y_train)
pred = ab.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)