# -*- coding: utf-8 -*-
"""Day7 part2 DecisionTreeClassifier Vid10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZcLnyhpOeCJs2DCQjGEbiaYCzDyrnWFW
"""

import pandas as pd
df = pd.read_csv('drug200.csv')
import seaborn as sns
import matplotlib.pyplot as plt
sns.countplot(data = df, x = 'Sex')
plt.show()

df.isna().sum()
df

df[df.duplicated()]
#df['Drug'].unique()

plt.figure(figsize = (10,10))
sns.histplot(df[df['Drug']== 'drugY']['Age'], color = 'green')
sns.histplot(df[df['Drug']== 'drugX']['Age'], color = 'red')
sns.histplot(df[df['Drug']== 'drugA']['Age'], color = 'purple')
sns.histplot(df[df['Drug']== 'drugB']['Age'], color = 'yellow')
sns.histplot(df[df['Drug']== 'drugC']['Age'], color = 'blue')

from sklearn.preprocessing import OrdinalEncoder
en = OrdinalEncoder()
df['Drug'] = en.fit_transform(df[['Drug']])
df['BP'] = en.fit_transform(df[['BP']])
df['Cholesterol'] = en.fit_transform(df[['Cholesterol']])
df['Sex'] = en.fit_transform(df[['Sex']])
#df['Drug'].unique()
df

X = df.iloc[:, 0: -1]
y = df.iloc[:, -1]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

from sklearn.tree import DecisionTreeClassifier
clf_gini = DecisionTreeClassifier(criterion = 'gini', random_state =0)
clf_gini.fit(X_train, y_train)
pred = clf_gini.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

from sklearn import tree
plt.figure(figsize = (10,10))
tree.plot_tree(clf_gini.fit(X_train, y_train))
plt.show

clf_entropy = DecisionTreeClassifier(criterion = 'entropy', max_depth = 2, random_state = 0)
clf_entropy.fit(X_train, y_train)
pred = clf_entropy.predict(X_test)
accuracy_score(y_test, pred)

tree.plot_tree(clf_entropy.fit(X_train,y_train))