# -*- coding: utf-8 -*-
"""day7 GaussianNaiveBayesClassification vid9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u7h7lxIQxrycBsYCuFLTjbyh5IfQfbA_
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv('heart.csv')
df[df.duplicated()]
df.drop_duplicates(keep = 'first', inplace = True)
x = df['sex'].value_counts()
print(f"No. of males and females are {x[1]} and {x[0]}")
sns.countplot(data = df, x = 'sex')
plt.show()

plt.figure(figsize = (10,10))
sns.distplot(df[df['output']==True]['age'], color = 'green', kde = True)
plt.title('Attack vs Age')
plt.show()

y = df.iloc[:, -1].values
x = df.iloc[:, 1 : -1].values
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size = 0.25, random_state = 42)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
pred = gnb.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)