# -*- coding: utf-8 -*-
"""Day11 Vid16 HyperParameterTuning

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HG0o5dGvH7g8n-U4Kqc8W1zsbPfOvOSR

New HAPPY year !!!
"""

import pandas as pd
train = pd.read_csv('train_dataset.csv')
test = pd.read_csv('test_dataset.csv')
data = pd.merge(train, test)
data

df = data.iloc[: 400]
X = df.drop('smoking', axis = 1)
y = df['smoking']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)
pred = rfc.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

from sklearn.model_selection import GridSearchCV
forest_params = [{'max_depth': list(range(0, 15)), 'max_features': list(range(0,14))}]
clf = GridSearchCV(rfc, forest_params, cv = 10, scoring = 'accuracy')
clf.fit(X_train, y_train)
print(clf.best_score_)
print(clf.best_params_)

y_pred = clf.predict(X_test)
accuracy_score(y_test, pred)