# -*- coding: utf-8 -*-
"""day6 LogisticRegressionvid7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Yy2UnB5h2eEa02UBgeWBNB2AprTbRiH

Logistic Regression
"""

import pandas as pd
from sklearn.datasets import fetch_openml
df = fetch_openml('titanic', version = 1, as_frame = True)
X = df['data']
X['survived'] = df['target']
X.head()
y = df['target']

X.isnull().sum()
miss_val = pd.DataFrame(X.isnull().sum()/len(X)*100)
import seaborn as sns
miss_val.plot(kind='bar', title = 'Missing Value percentage', ylabel = 'percentage')

X.isnull().sum()

X.drop(['ticket', 'name'], axis = 1, inplace = True)
#imputation
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy = 'mean')
X['age'] = imp.fit_transform(X[['age']])
X['fare'] = imp.fit_transform(X[['fare']])
imp1 = SimpleImputer(strategy = 'most_frequent')
X['embarked'] = imp1.fit_transform(X[['embarked']])
embarked = pd.get_dummies(X['embarked'], drop_first = True)

X.drop(['embarked'], axis= 1, inplace = True)
X = pd.concat([X, embarked], axis =1)
X.drop(['home.dest'], axis = 1, inplace = True)
X.drop(['cabin', 'boat', 'body'], axis = 1, inplace = True)
X['sex'] = pd.get_dummies(X['sex'], drop_first = True)
X.head()

X['family']= X['sibsp'] + X['parch']
X.loc[X['family'] > 0, 'traveled_alone'] = 0
X.loc[X['family'] == 0, 'traveled_alone'] = 1
X.head()

X.drop(['sibsp', 'parch', 'family'], axis = 1, inplace = True)
X.head()

X.info()

from sklearn.model_selection import train_test_split
X.drop(['survived'], axis =1, inplace = True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 1)

from sklearn.linear_model import LogisticRegression
mod = LogisticRegression()
mod.fit(X_train, y_train)
pred = mod.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)